# Use an official Node.js LTS image
FROM node

# Set the working directory in the builder stage
WORKDIR /app

# Copy only the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .
# Expose the port your ReactJS app runs on
EXPOSE 3000

# Use an environment variable for the start command
CMD ["npm", "run", "dev"]
